ports:
    http: 8080
    debug: 5858

auth:
    jwt_secret: 'supersecret'

mongo:
    url: 'mongodb://127.0.0.1:27017/testDB'

facebook:
    clientID: 'clientID'
    clientSecret: 'clientSecret'
    callbackURL: 'http://localhost:8080/auth/facebook/callback'

# none/debug/info
loglevel: info